language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"

#services:
#  - mongodb

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell